services:
  - type: web
    name: business-analytics-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEEPSEEK_API_KEY
        fromSecret: true